apiVersion: v1
kind: Pod

metadata:
  name: redis-pod
  labels:
    app: redis
    role: master
spec:
  containers:
    - name: redis
      image: redis:alpine3.13
      ports:
        - containerPort: 6379
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: redis-service
spec:
  selector:
    app: redis
    role: master
  ports:
    - protocol: TCP
      port: 6379 # internal cluster port
      targetPort: 6379 # container port to sent requests to