apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pod
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: thomaspilgaard/youtube-dl-worker:0.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: youtube-downloader-configs
