apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce