apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-folder
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: /mnt/storagesrv/youtube/
